trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Install
    displayName: "Install Stage"
    jobs:
      - job: install_job
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: npm install
            workingDirectory: 'src'

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Install
    jobs:
      - job: test_job
        steps:
          - script: npm test
            workingDirectory: 'src'

  # ---------------------------
  # DEPLOY TO DEV
  # ---------------------------
  - stage: Deploy_Dev
    displayName: "Deploy to Dev"
    dependsOn: Test
    jobs:
      - deployment: DevDeploy
        displayName: "Dev Deployment Job"
        environment: "riddhi_demo_dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to DEV..."
                  workingDirectory: 'src'

  # ---------------------------
  # DEPLOY TO QA (with approval)
  # ---------------------------
  - stage: Deploy_QA
    displayName: "Deploy to QA"
    dependsOn: Deploy_Dev
    jobs:
      - deployment: QADeploy
        environment: "riddhi_demo_QA"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to QA..."
                  workingDirectory: 'src'

  # ---------------------------
  # DEPLOY TO PROD (manual approval)
  # ---------------------------
  - stage: Deploy_Prod
    displayName: "Deploy to Prod"
    dependsOn: Deploy_QA
    jobs:
      - deployment: ProdDeploy
        environment: "riddhi_demo_prod"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to PROD..."
                  workingDirectory: 'src'