trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: build
        displayName: "Build & Test Job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Install Node.js"

          - script: npm install
            displayName: "Install dependencies"

          - script: npm run build
            displayName: "Build"

          - script: npm test
            displayName: "Run Tests"

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: BuildAndTest
    jobs:
      - job: deploy
        displayName: "Deploy Job"
        steps:
          - script: echo "hello"
            displayName: "Print Hello for Deploy"